export enum MemberRolesEnum {
    PRESIDENT = 'PRESIDENT',
    EXECUTIVE_BODY = 'EXECUTIVE_BODY',
    ADMINISTRATION = 'ADMINISTRATION',
    SELECTION_COMMITTEE = 'SELECTION_COMMITTEE',
    CENSORSHIP_COMMITTEE = 'CENSORSHIP_COMMITTEE',
}